apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-echoer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-echoer
  template:
    metadata:
      labels:
        app: s3-echoer
    spec:
      serviceAccountName: s3-echoer
      containers:
      - name: main
        image: amazonlinux:2018.03
        command:
        - "sh"
        - "-c"
        - "curl -sL -o /s3-echoer https://github.com/mhausenblas/s3-echoer/releases/latest/download/s3-echoer-linux && chmod +x /s3-echoer && echo This is an in-cluster test | /s3-echoer s3-echoer-demo && sleep 10000"
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-west-2" 